/* Generated by scripts/generate-public-config.js — do not edit manually. */
window.__VEMIDI_PUBLIC_CONFIG__ = Object.freeze({
  "storeUrl": "https://vemidi-crafts.com",
  "productId": "d594ddce-2fb5-49e0-859d-9ff91e752b9d",
  "productSlug": "tvorcheski-komplekt-valshebni-peperudi",
  "landingUrl": "https://special.vemidi-crafts.com/valshebni-peperudi",
  "campaign": "butterflies",
  "source": "campaign-butterflies",
  "safeHandoffFallback": true
});
